version: '3.8'

services:
  textilflow-backend:
    build: .
    container_name: textilflow-spring
    ports:
      - "5001:8080"
    depends_on:
      - textilflow-mysql
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_HOST=textilflow-mysql
      - DB_PORT=3306
      - DB_NAME=textilflow-platform
      - DB_USERNAME=root
      - DB_PASSWORD=docker_mysql_password_2024
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: always
    networks:
      - textilflow-network

  textilflow-mysql:
    image: mysql:8.0
    container_name: textilflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker_mysql_password_2024
      MYSQL_DATABASE: textilflow-platform
      MYSQL_USER: textilflowuser
      MYSQL_PASSWORD: docker_mysql_password_2024
    ports:
      - "3307:3306"
    volumes:
      - textilflow_mysql_data:/var/lib/mysql
    restart: always
    networks:
      - textilflow-network

volumes:
  textilflow_mysql_data:

networks:
  textilflow-network:
    driver: bridge